### ISSUE TITLE
Missing documentation checklist

### ISSUE THREAD

**Issue by Gargron** [tootsuite/documentation#603]
- [x] Nginx HTTP proxy caching for Rails resources example
- [ ] Nginx HTTP proxy caching setup for S3/Wasabi/etc to reduce egress costs example
- [ ] Onion services setup in upcoming release example
- [ ] Setting up backups with borg? example

**Comment by levlaz** [comment]
Very cool, I've never heard of [borg](https://github.com/borgbackup/borg) before, its awesome! I'll give it a shot in my dev environment and write up a doc for this.
